_: {
  imports = [
    ./3d_printing.nix
    ./audio.nix
    ./boot.nix
    ./bt.nix
    ./dev.nix
    ./fonts.nix
    ./firmware.nix
    ./graphics.nix
    ./hm.nix
    ./hyprland.nix
    ./input.nix
    ./kernel.nix
    ./keyboard.nix
    ./locale.nix
    ./network
    ./nix.nix
    ./nvidia.nix
    ./obs.nix
    ./packages.nix
    ./printing.nix
    ./ram.nix
    ./security.nix
    ./session.nix
    ./storage.nix
    ./stylix.nix
    ./thunar.nix
    ./user.nix
    ./vm_host.nix
  ];
}
