{
  nixosHost,
  lib,
}: let
  inherit (lib.attrsets) filterAttrs mapAttrs;
  inherit (lib.lists) any remove;

  genPath = _host: folder: "~/${folder}";

  folders = {
    archive = {
      id = "retqm-3wvzg";
      devices = ["kdes" "klap" "sync"];
    };
    audio = {
      id = "eovpz-batvb";
      devices = ["kdes" "klap" "kpho" "sync"];
    };
    docs = {
      id = "hgqpn-ofxpf";
      devices = ["kdes" "klap" "kpho" "sync"];
    };
    kpho = {
      id = "eliin-ttr6c";
      devices = ["kpho" "sync"];
    };
    notes = {
      id = "uxacx-3e297";
      devices = ["kdes" "klap" "kpho" "sync"];
    };
    pics = {
      id = "3bzlc-rj7c4";
      devices = ["kdes" "klap" "kpho" "sync"];
    };
    stl = {
      id = "ctrjj-nrnx5";
      devices = ["kdes" "klap" "sync"];
    };
    vids = {
      id = "tk4vv-jkcpl";
      devices = ["kdes" "klap" "kpho" "sync"];
    };
  };
  # returns attrset of folders that have `nixosHost` in list of devices,
  # but with `nixosHost` removed from the list, as expected by syncthing,
  # and path attr injected, generated by function above (extensible later)
in
  mapAttrs
  (k: v:
    v
    // {
      devices = remove nixosHost v.devices;
      path = genPath nixosHost k;
    })
  (filterAttrs (_k: v: any (d: d == nixosHost) v.devices) folders)
